# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: Ping Artifactory
        run: jfrog rt ping

      - name: Build 
        run: jfrog pipi -r requirements.txt --no-cache-dir --force-reinstall  --build-name=action_python --build-name=1 --module=demo 

      - name: Package
        run: python setup.py sdist bdist_wheel -d build/ 

      - name: Upload package
        run: jfrog rt u build/ $ --build-name=action_python --build-name=1 --module=demo
        
      - name: Publish Build Information
        run: |
            # Collect environment variables for the build
            jfrog rt bce action_python 1
            # Collect VCS details from git and add them to the build
            jfrog rt bag action_python 1
            # Publish build info
            jfrog rt bp action_python
